# Generated by Django 3.2.15 on 2023-11-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentProviders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created Date and Time', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated Date and Time', verbose_name='Updated At')),
                ('name', models.CharField(max_length=254, verbose_name='Name of the content provider')),
                ('endpoint_url', models.URLField(max_length=254, verbose_name='API endpoint URL')),
            ],
            options={
                'verbose_name': 'Content Provider',
                'verbose_name_plural': 'Content Providers',
                'db_table': 'content_providers',
            },
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created Date and Time', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated Date and Time', verbose_name='Updated At')),
                ('title', models.CharField(max_length=254, verbose_name='Title of the Content')),
                ('short_description', models.CharField(max_length=254, verbose_name='Short description')),
                ('about', models.TextField(verbose_name='Full description an the content')),
                ('image_url', models.FileField(upload_to='content-images', verbose_name='Content Image URL')),
                ('external_content_url', models.URLField(max_length=254, verbose_name='External Content URL')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'db_table': 'contents',
            },
        ),
    ]
