# Generated by Django 3.2.15 on 2023-11-15 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contents_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contents',
            name='provider',
        ),
        migrations.DeleteModel(
            name='ContentProviders',
        ),
        migrations.DeleteModel(
            name='Contents',
        ),
    ]
