#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput

python /app/manage.py migrate

# A custom management command to create a superuser if not exists already.
python /app/manage.py createadminuser

/usr/local/bin/gunicorn config.asgi --bind 0.0.0.0:8080 --chdir=/app -k uvicorn.workers.UvicornWorker
